services:
  ytdl:
    image: ghcr.io/casapps/ytdl:devel
    container_name: ytdl-test
    hostname: ytdl-test
    restart: "no"
    ports:
      - "64582:80"
    volumes:
      - './rootfs/config:/config:z'
      - './rootfs/data:/data:z'
    environment:
      - TZ=America/New_York
      - MODE=development
      - DEBUG=true
    stop_signal: SIGRTMIN+3
    stop_grace_period: 10s
